
-- Script generated by SimpleSpy - credits to exx#9394




--  REBIRTH LEGENDS X 
getgenv().tap = false
getgenv().rebirth = false
getgenv().autoUpgrades = false
getgenv().autoPotion = false
getgenv().autoChests = false
getgenv().autoCraftAll = false
getgenv().CyberBoost = false
getgenv().autoEgg = false

local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("Rebirth Champions X", "BloodTheme")

local MainSection = Window:NewTab("Functions")
local MainSection = MainSection:NewSection("Main")
local EggSection = Window:NewTab("Egg Stuff")
local EggSection = EggSection:NewSection("Main")

local MainTeleport = Window:NewTab("Teleports")
local MainTeleport = MainTeleport:NewSection("Locations")
local MainMisc = Window:NewTab("Misc")
local MainMisc = MainMisc:NewSection("Misc")


-- FUNCTIONS
game:GetService"RunService".RenderStepped:Connect(function()
    local args = {[1] = "Heaven"}
game:GetService("ReplicatedStorage").Events.WorldBoost:FireServer(unpack(args))
wait(0.5)
    end)

   



MainSection:NewToggle("Auto Tap", "Toggles Auto Tap", function(state)
    getgenv().Tap = state 
if state then
  doTap()
  
end
end)

MainSection:NewToggle("Auto Rebirths", "Toggles Auto Rebirths", function(bool)
getgenv().rebirth = bool 
if bool then
    doRebirth(selectedRebirth)
end
end)

local selectedRebirth
MainSection:NewDropdown("Rebirth", "Auto Rebirths", {1, 2, 3, 4, 5, 6, 7 , 8, 9, 10, 11 , 12 , 13 , 14 , 15 , 16, 17, 18, 19, 20, 21, 22, 23}, function(value)
    selectedRebirth = value
    print(value)
    
    end)
    getgenv().autoEgg = true

EggSection:NewToggle("Auto Eggs", "Toggles Auto Eggs", function(bool)
getgenv().autoEgg = bool
    if bool then
        egg()
    end
end)

local selectedEgg
EggSection:NewDropdown("Egg", "Auto Egg", {"Basic", "Mythic", "Forest", "Beach", "Atlantis", "Desert", "Winter", "Volcano", "Magma", "Moon", "Cyber", "Magic", "Heaven" }, function(value)

selectedEgg = value
end)

EggSection:NewToggle("Auto Craft", "Toggles Auto Craft", function(autoCraft)
    getgenv().autoCraftAll = autoCraft
    if autoCraft then
        Craft()
    end
end)




    MainSection:NewToggle("Auto Upgrades", "Toggles Auto Upgrades", function(upgrades)
        getgenv().autoUpgrades = upgrades
        if upgrades then
            doUpgrades()
        end
    end)
    


    MainSection:NewToggle("Auto Potion", "Toggles Auto Potion", function(potion)
        getgenv().autoPotion = potion
        if potion then
            doPotion()
        end
    end)


function doTap()
    spawn(function()
        while getgenv().Tap == true do
            game:GetService("ReplicatedStorage").Events.Click3:FireServer()
            wait()
        end
    end)
end

function egg()
    spawn(function()
        while getgenv().autoEgg == true do
            

        
    local args = {
    [1] = selectedEgg,
    [2] = "Triple"
}
    wait()
game:GetService("ReplicatedStorage").Functions.Unbox:InvokeServer(unpack(args))
end
end)
end


function doRebirth()
    spawn(function()
        while getgenv().rebirth == true do
game:GetService("ReplicatedStorage").Events.Rebirth:FireServer(selectedRebirth)
wait()
        end
        
    end)
    
end


function  doUpgrades()
    spawn(function()
        while getgenv().autoUpgrades == true do
        local args = {[1] = "PetStorage"}

game:GetService("ReplicatedStorage").Functions.Upgrade:InvokeServer(unpack(args))
local args = {[1] = "LuckMultiplier"}
game:GetService("ReplicatedStorage").Functions.Upgrade:InvokeServer(unpack(args))
local args = {[1] = "GemsMultiplier"}
game:GetService("ReplicatedStorage").Functions.Upgrade:InvokeServer(unpack(args))
local args = {[1] = "WalkSpeed"}
game:GetService("ReplicatedStorage").Functions.Upgrade:InvokeServer(unpack(args))
local args = {[1] = "ClickMultiplier"}
game:GetService("ReplicatedStorage").Functions.Upgrade:InvokeServer(unpack(args))
local args = {[1] = "RebirthButtons"}
game:GetService("ReplicatedStorage").Functions.Upgrade:InvokeServer(unpack(args))
local args = {[1] = "FasterFreeAutoClicker"}
game:GetService("ReplicatedStorage").Functions.Upgrade:InvokeServer(unpack(args))
local args = {[1] = "FreeAutoClicker"}
game:GetService("ReplicatedStorage").Functions.Upgrade:InvokeServer(unpack(args))
local args = {[1] = "PetEquip"}
game:GetService("ReplicatedStorage").Functions.Upgrade:InvokeServer(unpack(args))
    wait(2.5)
    end
end)
end


function Craft()
    spawn(function()
        while getgenv().autoCraftAll == true do
local args = {
    [1] = "CraftAll",
    [2] = {}}
game:GetService("ReplicatedStorage").Functions.Request:InvokeServer(unpack(args))
wait(2)

        end
        
    end)
        
    end

function doPotion()
    spawn(function()
        while getgenv().autoPotion == true do
local args = {[1] = "x2Clicks"} 
game:GetService("ReplicatedStorage").Events.Potion:FireServer(unpack(args))
local args = {[1] = "x2Gems"} 
game:GetService("ReplicatedStorage").Events.Potion:FireServer(unpack(args))
local args = {[1] = "x2Luck"} 
game:GetService("ReplicatedStorage").Events.Potion:FireServer(unpack(args))
local args = {[1] = "x2Rebirths"}
game:GetService("ReplicatedStorage").Events.Potion:FireServer(unpack(args))

     wait()
        end
        
    end)
    
end

-- TELEPORTS

MainTeleport:NewButton("Spawn", "Teleports To Spawn", function()
    local pl = game.Players.LocalPlayer.Character.HumanoidRootPart 
    local location = CFrame.new(84.6955566, 6.05586386, 66.2401276, 1, 0, 0, 0, 1, 0, 0, 0, 1)
    local humanoid = game.Players.LocalPlayer.Character.Humanoid
    pl.CFrame = location
end)

MainTeleport:NewButton("Forest", "Teleports To Forest", function()
    local pl = game.Players.LocalPlayer.Character.HumanoidRootPart 
    local location = CFrame.new(-386.710175, 30.5047722, 175.198593, 1, 0, 0, 0, 1, 0, 0, 0, 1)
    local humanoid = game.Players.LocalPlayer.Character.Humanoid
    pl.CFrame = location
end)

MainTeleport:NewButton("Beach", "Teleports To Beach", function()
    local pl = game.Players.LocalPlayer.Character.HumanoidRootPart 
    local location = CFrame.new(-517.284119, 37.3794289, 458.350983, -0.881527901, 0, 0.472132653, 0, 1, 0, -0.472132653, 0, -0.881527901)
    local humanoid = game.Players.LocalPlayer.Character.Humanoid
    pl.CFrame = location
end)

MainTeleport:NewButton("Atlantis", "Teleports To Atlantis", function()
    local pl = game.Players.LocalPlayer.Character.HumanoidRootPart 
    local location = CFrame.new(40.450161, 9.20697689, 675.801208, -1.1920929e-07, 0, -1.00000012, 0, 1, 0, 1.00000012, 0, -1.1920929e-07)
    local humanoid = game.Players.LocalPlayer.Character.Humanoid
    pl.CFrame = location
end)

MainTeleport:NewButton("Desert", "Teleports To Desert", function()
    local pl = game.Players.LocalPlayer.Character.HumanoidRootPart 
    local location = CFrame.new(468.551819, 7.06227589, 703.342041, -1.1920929e-07, 0, -1.00000012, 0, 1, 0, 1.00000012, 0, -1.1920929e-07)
    local humanoid = game.Players.LocalPlayer.Character.Humanoid
    pl.CFrame = location
end)

MainTeleport:NewButton("Winter", "Teleports To Winter", function()
    local pl = game.Players.LocalPlayer.Character.HumanoidRootPart 
    local location = CFrame.new(1035.05212, -45.3936691, 165.007645, -1, 0, 0, 0, 1, 0, 0, 0, -1)
    local humanoid = game.Players.LocalPlayer.Character.Humanoid
    pl.CFrame = location
end)

MainTeleport:NewButton("Volcano", "Teleports To Volcano", function()
    local pl = game.Players.LocalPlayer.Character.HumanoidRootPart 
    local location = CFrame.new(1044.25806, -34.5096893, 595.829468, 0.454243124, -0, -0.890877783, 0, 1, -0, 0.890877783, 0, 0.454243124)
    local humanoid = game.Players.LocalPlayer.Character.Humanoid
    pl.CFrame = location
end)

MainTeleport:NewButton("Moon", "Teleports To Moon", function()
    local pl = game.Players.LocalPlayer.Character.HumanoidRootPart 
    local location = CFrame.new(-372.538025, 36.0676422, -184.185822, -0.99772203, 0, 0.0674653724, 0, 1, 0, -0.0674653724, 0, -0.99772203)
    local humanoid = game.Players.LocalPlayer.Character.Humanoid
    pl.CFrame = location
end)

MainTeleport:NewButton("Cyber", "Teleports To Cyber", function()
    local pl = game.Players.LocalPlayer.Character.HumanoidRootPart 
    local location = CFrame.new(-372.542877, 37.9760704, -476.731384, -0.99772203, 0, 0.0674653724, 0, 1, 0, -0.0674653724, 0, -0.99772203)
    local humanoid = game.Players.LocalPlayer.Character.Humanoid
    pl.CFrame = location
end)


MainTeleport:NewButton("Magic", "Teleports To Magic", function()
    local pl = game.Players.LocalPlayer.Character.HumanoidRootPart 
    local location = CFrame.new(-27.0092049, 37.9760704, -478.55072, -0.99772203, 0, 0.0674653724, 0, 1, 0, -0.0674653724, 0, -0.99772203)
    local humanoid = game.Players.LocalPlayer.Character.Humanoid
    pl.CFrame = location
end)


MainTeleport:NewButton("Heaven", "Teleports To Heaven", function()
    local pl = game.Players.LocalPlayer.Character.HumanoidRootPart 
    local location = CFrame.new(-372.538025, 36.067585, -757.216919, -0.99772203, 0, 0.0674653724, 0, 1, 0, -0.0674653724, 0, -0.99772203)
    local humanoid = game.Players.LocalPlayer.Character.Humanoid
    pl.CFrame = location
end)





-- MISC

MainMisc:NewSlider("WalkSpeed", "Changes WalkSpeed", 500, 16, function(s) -- 500 (MaxValue) | 0 (MinValue)
    game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = s
end)


MainMisc:NewButton("Auto Pet Machine", "Lucky Draw", function()
    game:GetService("ReplicatedStorage").Functions.Machine:InvokeServer()
end)

MainMisc:NewButton("Claim Chests", "Claims All Chests", function()
    local args = {[1] = "Spawn"}
game:GetService("ReplicatedStorage").Events.Chest:FireServer(unpack(args))

local args = {[1] = "Cyber"}

game:GetService("ReplicatedStorage").Events.Chest:FireServer(unpack(args))

local args = {[1] = "Beach"}

game:GetService("ReplicatedStorage").Events.Chest:FireServer(unpack(args))

local args = {[1] = "Winter"}

game:GetService("ReplicatedStorage").Events.Chest:FireServer(unpack(args))
    
        end)

MainMisc:NewButton("Credits: YourWaifuAstolfo#6809")
MainMisc:NewButton("UI: Kavo Library")
